CREATE TABLE sensor(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE measurement(
                            id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            value real NOT NULL,
                            raining boolean NOT NULL,
                            measured_at TIMESTAMP NOT NULL ,
                            sensor_name varchar(100) REFERENCES sensor(name) ON DELETE CASCADE NOT NULL
);